local addonName, addonTable = ...

local L = {}
addonTable.L = L

local function applyEnglish()
    L["craft_button"] = "Craft (%d)"
    L["craft_button_unavail"] = "Unavailable"
    L["not_learned"] = "Recipe not learned"
    L["profession_cap"] = "Profession cap reached"
    L["recipe_prefix"] = "Materials: "
    L["unknown_recipe_prefix"] = "Recipe: "
    L["header_label"] = "Profession Capper"
    L["loaded_for"] = "[Profession Capper] loaded for"
    L["crafting"] = "[Profession Capper] crafting"
    L["train_profession"] = "Train the next profession rank to continue"
    L["no_guide_step"] = "No guide step is available for this skill level"
    L["profession_progress"] = "%s  %d / %d"
    L["profession_progress_bonus"] = "%s  %d / %d  (+%d)"
    L["target_line"] = "Skill %d -> %d"
    L["stats_exact"] = "Need: %s  |  Can: %d  |  Crafts: %d"
    L["stats_minimum"] = "Need: %s  |  Can: %d  |  Crafts: at least %d"
    L["stats_unlearned"] = "Need: %s"
    L["eta_exact"] = "Estimated time: %s"
    L["eta_minimum"] = "Minimum time: %s"
    L["eta_unavailable"] = "Estimated time: unavailable"
    L["craft_to"] = "Craft to %d"
    L["continue_to"] = "Continue to %d"
    L["crafting_button"] = "Crafting..."
    L["craft_progress"] = "Crafting %d/%d  |  ~%s left"
    L["craft_progress_no_eta"] = "Crafting %d/%d"
    L["craft_batch_done"] = "Batch complete  |  %s still needed"
    L["target_reached"] = "Target reached"
    L["recipe_position"] = "%d / %d"
    L["skill_up_one"] = "1 skill-up"
    L["skill_up_many"] = "%d skill-ups"
    L["recipe_not_learned"] = "Recipe not learned"
    L["missing_materials"] = "Missing materials"
    L["materials_label"] = "Materials"
    L["material_tooltip_hint"] = "Shift-Right-Click: put this item in the Auction House search"
    L["auction_house_not_open"] = "Open the Auction House browse tab first"
    L["mode_cheapest"] = "Cheapest now"
    L["mode_static"] = "Static guide"
    L["route_button"] = "Compare"
    L["dynamic_preferred"] = "Cheapest usable learned recipe with current prices"
    L["dynamic_stats"] = "Expected: ~%d crafts  |  Can: %d  |  Segment: ~%s"
    L["dynamic_price_line"] = "%s  |  %s  |  scan %s"
    L["dynamic_quality_current"] = "current prices"
    L["dynamic_quality_stale"] = "stale prices"
    L["dynamic_total_cap"] = "Estimated to cap: ~%s  |  Gold now: ~%s  |  ~%d crafts"
    L["dynamic_total_rank"] = "Estimated to %d: ~%s  |  Gold now: ~%s  |  ~%d crafts"
    L["dynamic_per_application"] = "Per application: ~%s  |  Expected / skill-up: ~%s"
    L["dynamic_route_total"] = "To %d: ~%s total  |  Buy missing: ~%s  |  ~%d crafts"
    L["dynamic_current_only"] = "Cheapest current step to %d; full-route total unavailable"
    L["dynamic_stale_count"] = "%d stale"
    L["dynamic_missing_count"] = "%d missing/unpriced"
    L["dynamic_fallback"] = "Cheapest now unavailable (%s). Showing Static guide."
    L["static_summary"] = "Static guide · current-price optimization off"
    L["dynamic_reason_no_prices"] = "no usable price data"
    L["dynamic_reason_no_recipes"] = "no safely modeled learned recipes"
    L["dynamic_reason_no_route"] = "no complete priced route"
    L["dynamic_reason_missing_prices"] = "missing material prices"
    L["dynamic_reason_unknown"] = "insufficient data"
    L["craft_toward"] = "Craft toward %d"
    L["material_no_price"] = "No price"
    L["material_price_unit"] = "Unit price: %s"
    L["material_price_remaining"] = "Estimated remaining cost: %s"
    L["material_price_source"] = "%s · %s · %s"
    L["material_price_conversion"] = "Cheapest equivalent: %s"
    L["material_buy_instead"] = "Buy %dx %s instead"
    L["material_buy_instead_savings"] = "Buy %dx %s instead · save ~%s"
    L["material_buy_better_title"] = "Cheaper purchase option"
    L["material_buy_conversion"] = "%dx %s covers %dx %s"
    L["material_buy_compare"] = "Direct: ~%s  |  Recommended: ~%s"
    L["material_buy_savings"] = "You save ~%s"
    L["material_price_missing"] = "Price unavailable: %s"
    L["acquisition_prefix"] = "Get recipe: "
    L["acquisition_unknown"] = "Recipe not learned · acquisition source unknown"
    L["acquisition_trainer"] = "Trainer"
    L["acquisition_vendor"] = "Vendor"
    L["acquisition_limited_vendor"] = "Limited-stock vendor"
    L["acquisition_auction"] = "Auction House"
    L["acquisition_reputation"] = "Reputation"
    L["acquisition_quest"] = "Quest"
    L["acquisition_drop"] = "Drop"
    L["acquisition_manual"] = "Manual source"
    L["acquisition_limited_stock"] = "limited stock"
    L["compare_tooltip_title"] = "Compared skill-up recipes now"
    L["compare_tooltip_recipe"] = "%s  ·  %s  ·  ~%s/application  ·  ~%s/skill-up"
    L["compare_tooltip_more"] = "+%d more usable recipes"
    L["route_tooltip_title"] = "Full estimated route"
    L["route_tooltip_incomplete"] = "Full route unavailable; current-step recommendation is still valid."
    L["route_tooltip_craft"] = "%d-%d  %s  ·  ~%d crafts  ·  ~%s"
    L["route_tooltip_training"] = "Train %d -> %d  ·  %s"
    L["route_tooltip_more"] = "+%d more segments"
    L["repeat_label"] = "Repeat:"
    L["repeat_until_change"] = "Until change"
    L["repeat_fixed"] = "Fixed count"
    L["enchant_until_change"] = "Enchant until change"
    L["enchant_fixed"] = "Enchant (%d)"
    L["enchant_again"] = "Enchant again"
    L["enchant_again_fixed"] = "Enchant again (%d/%d)"
    L["enchanting_button"] = "Enchanting..."
    L["enchant_select_target"] = "Select the item to enchant; it will be remembered"
    L["enchant_applying"] = "Applying enchant..."
    L["enchant_repeat_progress_fixed"] = "%d/%d applied · click Enchant again"
    L["enchant_repeat_progress_auto"] = "%d applied · continue until recommendation changes"
    L["enchant_repeat_complete"] = "Repeat complete · %d/%d applied"
    L["enchant_started_fixed"] = "[Profession Capper] enchanting application %d/%d:"
    L["enchant_started_auto"] = "[Profession Capper] enchanting; repeat until recommendation changes:"
end

local function applySpanish()
    L["craft_button"] = "Fabricar (%d)"
    L["craft_button_unavail"] = "No disponible"
    L["not_learned"] = "No aprendida o no disponible"
    L["profession_cap"] = "Nivel máximo de profesión alcanzado"
    L["recipe_prefix"] = "Materiales: "
    L["unknown_recipe_prefix"] = "Receta: "
    L["loaded_for"] = "[Profession Capper] cargado para"
    L["crafting"] = "[Profession Capper] fabricando"
    L["train_profession"] = "Entrena el siguiente rango de profesión para continuar"
    L["no_guide_step"] = "No hay un paso de guía para este nivel"
    L["profession_progress"] = "%s  %d / %d"
    L["profession_progress_bonus"] = "%s  %d / %d  (+%d)"
    L["target_line"] = "Habilidad %d -> %d"
    L["stats_exact"] = "Faltan: %s  |  Puedes: %d  |  Fabricaciones: %d"
    L["stats_minimum"] = "Faltan: %s  |  Puedes: %d  |  Fabricaciones: al menos %d"
    L["stats_unlearned"] = "Faltan: %s"
    L["eta_exact"] = "Tiempo estimado: %s"
    L["eta_minimum"] = "Tiempo mínimo: %s"
    L["eta_unavailable"] = "Tiempo estimado: no disponible"
    L["craft_to"] = "Fabricar hasta %d"
    L["continue_to"] = "Continuar hasta %d"
    L["crafting_button"] = "Fabricando..."
    L["craft_progress"] = "Fabricando %d/%d · ~%s restantes"
    L["craft_progress_no_eta"] = "Fabricando %d/%d"
    L["craft_batch_done"] = "Lote terminado  |  faltan %s"
    L["target_reached"] = "Objetivo alcanzado"
    L["skill_up_one"] = "1 punto"
    L["skill_up_many"] = "%d puntos"
    L["recipe_not_learned"] = "Receta no aprendida"
    L["missing_materials"] = "Faltan materiales"
    L["materials_label"] = "Materiales"
    L["material_tooltip_hint"] = "Mayús-Clic derecho: poner este objeto en la búsqueda de la Casa de Subastas"
    L["auction_house_not_open"] = "Abre primero la pestaña de búsqueda de la Casa de Subastas"
end

local function applyRussian()
    L["craft_button"] = "Изготовить (%d)"
    L["craft_button_unavail"] = "Недоступно"
    L["not_learned"] = "Не изучен или недоступен"
    L["profession_cap"] = "Достигнут максимум профессии"
    L["recipe_prefix"] = "Материалы: "
    L["unknown_recipe_prefix"] = "Рецепт: "
    L["loaded_for"] = "[Profession Capper] загружен для"
    L["crafting"] = "[Profession Capper] изготовление"
    L["train_profession"] = "Изучите следующий ранг профессии, чтобы продолжить"
    L["no_guide_step"] = "Для этого уровня навыка нет шага руководства"
    L["profession_progress"] = "%s  %d / %d"
    L["profession_progress_bonus"] = "%s  %d / %d  (+%d)"
    L["target_line"] = "Навык %d -> %d"
    L["stats_exact"] = "Нужно: %s  |  Можно: %d  |  Создать: %d"
    L["stats_minimum"] = "Нужно: %s  |  Можно: %d  |  Создать: минимум %d"
    L["stats_unlearned"] = "Нужно: %s"
    L["eta_exact"] = "Примерное время: %s"
    L["eta_minimum"] = "Минимальное время: %s"
    L["eta_unavailable"] = "Примерное время: недоступно"
    L["craft_to"] = "Создать до %d"
    L["continue_to"] = "Продолжить до %d"
    L["crafting_button"] = "Создание..."
    L["craft_progress"] = "Создание %d/%d · ~%s осталось"
    L["craft_progress_no_eta"] = "Создание %d/%d"
    L["craft_batch_done"] = "Партия завершена  |  осталось %s"
    L["target_reached"] = "Цель достигнута"
    L["skill_up_one"] = "1 очко"
    L["skill_up_many"] = "%d очк."
    L["recipe_not_learned"] = "Рецепт не изучен"
    L["missing_materials"] = "Не хватает материалов"
    L["materials_label"] = "Материалы"
    L["material_tooltip_hint"] = "Shift-ПКМ: вставить предмет в поиск аукциона"
    L["auction_house_not_open"] = "Сначала откройте вкладку поиска аукциона"
end

function addonTable.applyLocale()
    applyEnglish()

    local locale = GetLocale()
    if locale == "esES" or locale == "esMX" then
        applySpanish()
    elseif locale == "ruRU" then
        applyRussian()
    end

    if addonTable.applyRecipeLocale then
        addonTable.applyRecipeLocale()
    end
end
