#!/usr/bin/env python3
"""Generate compact profession route-topology events from difficulty metadata."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "RecipeDifficultyData.lua"
OUTPUT = ROOT / "GeneratedRouteData.lua"

PROFESSION_RE = re.compile(r'\["([^"]+)"\]\s*=\s*\{([\s\S]*?)\n\s*\},')
ROW_RE = re.compile(r"\{(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\}")
REVISION_RE = re.compile(r'recipeDifficultyDataRevision\s*=\s*"([^"]+)"')


def parse_source(text: str):
    professions: dict[str, list[tuple[int, int, int]]] = {}
    for match in PROFESSION_RE.finditer(text):
        rows = []
        for row in ROW_RE.finditer(match.group(2)):
            spell_id, required, _yellow, _green, gray = map(int, row.groups())
            rows.append((spell_id, required, gray))
        if rows:
            professions[match.group(1)] = rows

    revision_match = REVISION_RE.search(text)
    if not revision_match:
        raise RuntimeError("RecipeDifficultyData.lua has no revision")
    return professions, revision_match.group(1)


def render(professions, revision: str) -> str:
    lines = [
        "local addonName, addonTable = ...",
        "",
        "-- Generated by tools/generate_route_data.py from RecipeDifficultyData.lua.",
        "-- Do not hand-edit. Each recipe appears once at its required-skill start",
        "-- and once at its gray-skill stop so runtime candidate indexes can be built",
        "-- without rescanning all recipe metadata on every profession-window open.",
        f'addonTable.generatedRouteTopologyRevision = "route-v1:{revision}"',
        "addonTable.generatedRouteTopology = {",
    ]

    for profession in sorted(professions):
        starts: dict[int, list[int]] = defaultdict(list)
        stops: dict[int, list[int]] = defaultdict(list)
        for spell_id, required, gray in professions[profession]:
            starts[required].append(spell_id)
            stops[gray].append(spell_id)

        lines.append(f'    ["{profession}"] = {{')
        for label, events in (("starts", starts), ("stops", stops)):
            lines.append(f"        {label} = {{")
            for skill in sorted(events):
                ids = ", ".join(str(value) for value in sorted(events[skill]))
                lines.append(f"            [{skill}] = {{ {ids} }},")
            lines.append("        },")
        lines.append("    },")

    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    source = SOURCE.read_text(encoding="utf-8")
    professions, revision = parse_source(source)
    generated = render(professions, revision)

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print("GeneratedRouteData.lua is stale; run tools/generate_route_data.py")
            return 1
        print("Generated route topology is up to date.")
        return 0

    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
